name: Maven to EXE

on:
  push:
    branches:
      - main  # Ejecuta el workflow en cada commit a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Compilar con Maven
      run: mvn -B package --file pom.xml

    - name: Instalar Launch4j
      run: |
        wget http://sourceforge.net/projects/launch4j/files/latest/download -O launch4j.zip
        unzip launch4j.zip -d launch4j

    - name: Convertir JAR a EXE
      run: |
        launch4j/launch4j resources/app_configuration_launch4j.xml

    - name: Renombrar ejecutable
      run: mv resources/Subcafae.exe "Subcafae - HSJv0.0.2.exe"

    - name: Subir ejecutable
      uses: actions/upload-artifact@v4
      with:
        name: Subcafae-HSJv0.0.2
        path: "Subcafae - HSJv0.0.2.exe"